import { library } from '@fortawesome/fontawesome-svg-core';

import {
	faChevronUp,
	faChevronDown,
	faChevronRight,
	faArrowRight,
	faArrowLeft,
	faXmark,
	faGear,
	faSearch,
	faEnvelopeCircleCheck,
	faCircleCheck,
	faCar,
	faGasPump,
	faChargingStation,
	faBookBookmark,
	faGears,
	faAddressCard,
	faGauge,
	faEllipsis,
	faWrench,
	faFileInvoiceDollar,
	faBattery2,
	faBatteryFull,
	faPlugCircleBolt,
	faWarning,
	faOilCan,
} from '@fortawesome/free-solid-svg-icons';

import {
	faCircleDot as faCircleDotRegular,
	faEye as faEyeRegular,
	faEyeSlash as faEyeSlashRegular,
	faCircleXmark as faCircleXmarkRegular,
	faCircleCheck as faCircleCheckRegular,
} from '@fortawesome/free-regular-svg-icons';

library.add(
	faChevronUp,
	faChevronDown,
	faChevronRight,
	faArrowLeft,
	faArrowRight,
	faXmark,
	faGear,
	faSearch,
	faEyeRegular,
	faEyeSlashRegular,
	faCircleDotRegular,
	faEnvelopeCircleCheck,
	faCircleCheck,
	faCar,
	faGasPump,
	faChargingStation,
	faBookBookmark,
	faGears,
	faAddressCard,
	faGauge,
	faEllipsis,
	faCircleXmarkRegular,
	faWrench,
	faFileInvoiceDollar,
	faCircleCheckRegular,
	faBattery2,
	faBatteryFull,
	faPlugCircleBolt,
	faWarning,
	faOilCan,
);

export default library;
